version: "3"
services:
  pets_api:
    container_name: pets_api
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - pets_mongo
    environment:
      - MONGO_URI=mongodb://pets_mongo:27017/pets
      - MONGO_URI_TEST=mongodb://pets_mongo:27017/pets-test
      - APP_ID=pets
      - PORT=3000
      - LOG_LEVEL=debug
      - REQUEST_LIMIT=100kb
      - SESSION_SECRET=mySecret
      - OPENAPI_SPEC=/api/v1/spec
      - OPENAPI_ENABLE_RESPONSE_VALIDATION=false
  pets_mongo:
    container_name: pets_mongo
    image: mongo
    ports:
      - "27017:27017"